### ISSUE TITLE
Font loading error

### ISSUE THREAD

**Issue by aiexz** [arynyklas/tetris-gui#1]
OS: Mac OS 13.3.1 
Python Version: 3.10.11

Error: 
```py
Traceback (most recent call last):
  File "/Users/alex/tetris-gui/game.py", line 698, in <module>
    main()
  File "/Users/alex/tetris-gui/game.py", line 688, in main
    main_window: MainWindow = MainWindow(
  File "/Users/alex/tetris-gui/game.py", line 76, in __init__
    QFontDatabase.applicationFontFamilies(
IndexError: list index out of range
```

**Comment by aiexz** [comment]
Managed to fix it by removing https://github.com/arynyklas/tetris-gui/blob/c9761734fc5fd9e6aaa4ed26d4d8029212206607/game.py#L75-L79 and https://github.com/arynyklas/tetris-gui/blob/c9761734fc5fd9e6aaa4ed26d4d8029212206607/game.py#L85-L87

**Comment by arynyklas** [comment]
Thank you for your report!
Fixed.
