### ISSUE TITLE
Unexpectedly closing when row is complete

### ISSUE THREAD

**Issue by aiexz** [arynyklas/tetris-gui#2]
OS: MacOS 13.3.1 
Python version: Python 3.10.11: 
<details>
<summary> Screenshot </summary>

<img width="382" alt="image" src="https://github.com/arynyklas/tetris-gui/assets/42418433/e7c0a7ca-0f37-482b-b9ac-0b076e6549cc">

</details>

Description of a problem: I hit space key for the piece to fall down and complete the row, but the program quits and returns a traceback
```py
Traceback (most recent call last):
  File "/Users/alex/tetris-gui/game.py", line 336, in keyPressEvent
    self.drop_down()
  File "/Users/alex/tetris-gui/game.py", line 369, in drop_down
    self.piece_dropped()
  File "/Users/alex/tetris-gui/game.py", line 391, in piece_dropped
    self.remove_full_lines()
  File "/Users/alex/tetris-gui/game.py", line 429, in remove_full_lines
    shape = self.get_shape_at(
  File "/Users/alex/tetris-gui/game.py", line 208, in get_shape_at
    return self.board[(y * self.BASE_SQUARE_WIDTH) + x]
IndexError: list index out of range
```

**Comment by aiexz** [comment]
Swapping x and y helped.
https://github.com/arynyklas/tetris-gui/blob/f703cea23dbc13fa8e4bd37d4597798f867a3349/game.py#L422-L423

**Comment by aiexz** [comment]
Let's take for example
https://github.com/arynyklas/tetris-gui/blob/8ecfc90cf304501a8df58d39cfe4c81d802a9376/game.py#L423
https://github.com/arynyklas/tetris-gui/blob/8ecfc90cf304501a8df58d39cfe4c81d802a9376/game.py#L205-L206

`Y` is multiplied by width, so `Y` has to be width, but we can see that in `for` `X` is used for width
